name: chilli
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  cloud_firestore: ^6.3.0
  google_sign_in: ^7.2.0
  firebase_auth: ^6.4.0
  shared_preferences: ^2.5.5
  intl: ^0.20.2
  uuid: ^4.5.3
  flutter_webrtc: ^1.4.1
  permission_handler: ^12.0.1
  firebase_database: ^12.3.0
  connectivity_plus: ^7.1.1
  audioplayers: ^6.6.0
  wakelock_plus: ^1.6.0
  google_mlkit_face_detection: ^0.13.2
  camera: ^0.12.0+1
  google_mlkit_image_labeling: ^0.14.2
  screen_brightness: ^2.1.7
  fluttertoast: ^9.0.0
  image_picker: ^1.2.1
  share_plus: ^13.0.0
  url_launcher: ^6.3.2
  flutter_image_compress: ^2.4.0
  facebook_app_events: ^0.27.0
  flutter_local_notifications: ^21.0.0
  firebase_analytics: ^12.3.0
  firebase_storage: ^13.3.0
  googleapis_auth: ^2.0.0
  archive: ^4.0.9
  firebase_messaging: ^16.2.0
  in_app_review: ^2.0.11
  firebase_app_check: ^0.4.3
  flutter_localizations:
    sdk: flutter
  screen_protector: ^1.5.1
  scratcher: ^2.5.0
  flutter_native_splash: ^2.4.7
  paygic: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/service-account.json

flutter_native_splash:
  color: "#0F0A1E"
  image: assets/logo.png
  android_12:
    color: "#0F0A1E"
    image: assets/logo.png
    icon_background_color: "#0F0A1E"
  android: true
  ios: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
